"""Add foreign keys and production constraints

Revision ID: 020dd8e698c1
Revises: 
Create Date: 2026-03-29 15:17:38.282302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020dd8e698c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'scrape_jobs', ['scrape_job_id'], ['id'])
    op.create_index('idx_scrape_jobs_sector', 'scrape_jobs', ['sector'], unique=False)
    op.create_index('idx_scrape_jobs_started_at', 'scrape_jobs', ['started_at'], unique=False)
    op.create_index('idx_scrape_jobs_user_id', 'scrape_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scrape_jobs_user_id', table_name='scrape_jobs')
    op.drop_index('idx_scrape_jobs_started_at', table_name='scrape_jobs')
    op.drop_index('idx_scrape_jobs_sector', table_name='scrape_jobs')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # ### end Alembic commands ###
